# Generated by Django 4.2.2 on 2023-07-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
