# Generated by Django 4.2.2 on 2023-07-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0002_remove_project_image_project_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='githublink',
            field=models.URLField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='livelink',
            field=models.URLField(default=0),
        ),
    ]
