# Generated by Django 4.1 on 2023-07-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0004_remove_project_video_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
