# Generated by Django 4.2.2 on 2023-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0006_alter_project_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies_used',
            field=models.CharField(default='', max_length=100),
        ),
    ]
