# Generated by Django 4.1 on 2023-08-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalsite', '0007_project_technologies_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='githublink',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='livelink',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(default=0, upload_to='media/'),
        ),
    ]
